/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTenantRouteImport } from './routes/t/$tenant'
import { Route as TTenantSettingsRouteImport } from './routes/t/$tenant/settings'
import { Route as TTenantRoutesRouteImport } from './routes/t/$tenant/routes'
import { Route as TTenantReportsRouteImport } from './routes/t/$tenant/reports'
import { Route as TTenantPaymentsRouteImport } from './routes/t/$tenant/payments'
import { Route as TTenantInvoicesRouteImport } from './routes/t/$tenant/invoices'
import { Route as TTenantDashboardRouteImport } from './routes/t/$tenant/dashboard'
import { Route as TTenantCustomersRouteImport } from './routes/t/$tenant/customers'
import { Route as TTenantAdminRouteImport } from './routes/t/$tenant/admin'
import { Route as TTenantAdminUsersRouteImport } from './routes/t/$tenant/admin/users'
import { Route as TTenantAdminSystemRouteImport } from './routes/t/$tenant/admin/system'
import { Route as TTenantAdminSupportRouteImport } from './routes/t/$tenant/admin/support'
import { Route as TTenantAdminBillingRouteImport } from './routes/t/$tenant/admin/billing'
import { Route as TTenantAdminAuditRouteImport } from './routes/t/$tenant/admin/audit'
import { Route as TTenantAdminAgentRouteImport } from './routes/t/$tenant/admin/agent'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantRoute = TTenantRouteImport.update({
  id: '/t/$tenant',
  path: '/t/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const TTenantSettingsRoute = TTenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantRoutesRoute = TTenantRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantReportsRoute = TTenantReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantPaymentsRoute = TTenantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantInvoicesRoute = TTenantInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantDashboardRoute = TTenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantCustomersRoute = TTenantCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantAdminRoute = TTenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TTenantRoute,
} as any)
const TTenantAdminUsersRoute = TTenantAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TTenantAdminRoute,
} as any)
const TTenantAdminSystemRoute = TTenantAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => TTenantAdminRoute,
} as any)
const TTenantAdminSupportRoute = TTenantAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => TTenantAdminRoute,
} as any)
const TTenantAdminBillingRoute = TTenantAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => TTenantAdminRoute,
} as any)
const TTenantAdminAuditRoute = TTenantAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => TTenantAdminRoute,
} as any)
const TTenantAdminAgentRoute = TTenantAdminAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => TTenantAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/t/$tenant/admin': typeof TTenantAdminRouteWithChildren
  '/t/$tenant/customers': typeof TTenantCustomersRoute
  '/t/$tenant/dashboard': typeof TTenantDashboardRoute
  '/t/$tenant/invoices': typeof TTenantInvoicesRoute
  '/t/$tenant/payments': typeof TTenantPaymentsRoute
  '/t/$tenant/reports': typeof TTenantReportsRoute
  '/t/$tenant/routes': typeof TTenantRoutesRoute
  '/t/$tenant/settings': typeof TTenantSettingsRoute
  '/t/$tenant/admin/agent': typeof TTenantAdminAgentRoute
  '/t/$tenant/admin/audit': typeof TTenantAdminAuditRoute
  '/t/$tenant/admin/billing': typeof TTenantAdminBillingRoute
  '/t/$tenant/admin/support': typeof TTenantAdminSupportRoute
  '/t/$tenant/admin/system': typeof TTenantAdminSystemRoute
  '/t/$tenant/admin/users': typeof TTenantAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/t/$tenant/admin': typeof TTenantAdminRouteWithChildren
  '/t/$tenant/customers': typeof TTenantCustomersRoute
  '/t/$tenant/dashboard': typeof TTenantDashboardRoute
  '/t/$tenant/invoices': typeof TTenantInvoicesRoute
  '/t/$tenant/payments': typeof TTenantPaymentsRoute
  '/t/$tenant/reports': typeof TTenantReportsRoute
  '/t/$tenant/routes': typeof TTenantRoutesRoute
  '/t/$tenant/settings': typeof TTenantSettingsRoute
  '/t/$tenant/admin/agent': typeof TTenantAdminAgentRoute
  '/t/$tenant/admin/audit': typeof TTenantAdminAuditRoute
  '/t/$tenant/admin/billing': typeof TTenantAdminBillingRoute
  '/t/$tenant/admin/support': typeof TTenantAdminSupportRoute
  '/t/$tenant/admin/system': typeof TTenantAdminSystemRoute
  '/t/$tenant/admin/users': typeof TTenantAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/t/$tenant': typeof TTenantRouteWithChildren
  '/t/$tenant/admin': typeof TTenantAdminRouteWithChildren
  '/t/$tenant/customers': typeof TTenantCustomersRoute
  '/t/$tenant/dashboard': typeof TTenantDashboardRoute
  '/t/$tenant/invoices': typeof TTenantInvoicesRoute
  '/t/$tenant/payments': typeof TTenantPaymentsRoute
  '/t/$tenant/reports': typeof TTenantReportsRoute
  '/t/$tenant/routes': typeof TTenantRoutesRoute
  '/t/$tenant/settings': typeof TTenantSettingsRoute
  '/t/$tenant/admin/agent': typeof TTenantAdminAgentRoute
  '/t/$tenant/admin/audit': typeof TTenantAdminAuditRoute
  '/t/$tenant/admin/billing': typeof TTenantAdminBillingRoute
  '/t/$tenant/admin/support': typeof TTenantAdminSupportRoute
  '/t/$tenant/admin/system': typeof TTenantAdminSystemRoute
  '/t/$tenant/admin/users': typeof TTenantAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/t/$tenant'
    | '/t/$tenant/admin'
    | '/t/$tenant/customers'
    | '/t/$tenant/dashboard'
    | '/t/$tenant/invoices'
    | '/t/$tenant/payments'
    | '/t/$tenant/reports'
    | '/t/$tenant/routes'
    | '/t/$tenant/settings'
    | '/t/$tenant/admin/agent'
    | '/t/$tenant/admin/audit'
    | '/t/$tenant/admin/billing'
    | '/t/$tenant/admin/support'
    | '/t/$tenant/admin/system'
    | '/t/$tenant/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/t/$tenant'
    | '/t/$tenant/admin'
    | '/t/$tenant/customers'
    | '/t/$tenant/dashboard'
    | '/t/$tenant/invoices'
    | '/t/$tenant/payments'
    | '/t/$tenant/reports'
    | '/t/$tenant/routes'
    | '/t/$tenant/settings'
    | '/t/$tenant/admin/agent'
    | '/t/$tenant/admin/audit'
    | '/t/$tenant/admin/billing'
    | '/t/$tenant/admin/support'
    | '/t/$tenant/admin/system'
    | '/t/$tenant/admin/users'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/t/$tenant'
    | '/t/$tenant/admin'
    | '/t/$tenant/customers'
    | '/t/$tenant/dashboard'
    | '/t/$tenant/invoices'
    | '/t/$tenant/payments'
    | '/t/$tenant/reports'
    | '/t/$tenant/routes'
    | '/t/$tenant/settings'
    | '/t/$tenant/admin/agent'
    | '/t/$tenant/admin/audit'
    | '/t/$tenant/admin/billing'
    | '/t/$tenant/admin/support'
    | '/t/$tenant/admin/system'
    | '/t/$tenant/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TTenantRoute: typeof TTenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenant': {
      id: '/t/$tenant'
      path: '/t/$tenant'
      fullPath: '/t/$tenant'
      preLoaderRoute: typeof TTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tenant/settings': {
      id: '/t/$tenant/settings'
      path: '/settings'
      fullPath: '/t/$tenant/settings'
      preLoaderRoute: typeof TTenantSettingsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/routes': {
      id: '/t/$tenant/routes'
      path: '/routes'
      fullPath: '/t/$tenant/routes'
      preLoaderRoute: typeof TTenantRoutesRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/reports': {
      id: '/t/$tenant/reports'
      path: '/reports'
      fullPath: '/t/$tenant/reports'
      preLoaderRoute: typeof TTenantReportsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/payments': {
      id: '/t/$tenant/payments'
      path: '/payments'
      fullPath: '/t/$tenant/payments'
      preLoaderRoute: typeof TTenantPaymentsRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/invoices': {
      id: '/t/$tenant/invoices'
      path: '/invoices'
      fullPath: '/t/$tenant/invoices'
      preLoaderRoute: typeof TTenantInvoicesRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/dashboard': {
      id: '/t/$tenant/dashboard'
      path: '/dashboard'
      fullPath: '/t/$tenant/dashboard'
      preLoaderRoute: typeof TTenantDashboardRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/customers': {
      id: '/t/$tenant/customers'
      path: '/customers'
      fullPath: '/t/$tenant/customers'
      preLoaderRoute: typeof TTenantCustomersRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/admin': {
      id: '/t/$tenant/admin'
      path: '/admin'
      fullPath: '/t/$tenant/admin'
      preLoaderRoute: typeof TTenantAdminRouteImport
      parentRoute: typeof TTenantRoute
    }
    '/t/$tenant/admin/users': {
      id: '/t/$tenant/admin/users'
      path: '/users'
      fullPath: '/t/$tenant/admin/users'
      preLoaderRoute: typeof TTenantAdminUsersRouteImport
      parentRoute: typeof TTenantAdminRoute
    }
    '/t/$tenant/admin/system': {
      id: '/t/$tenant/admin/system'
      path: '/system'
      fullPath: '/t/$tenant/admin/system'
      preLoaderRoute: typeof TTenantAdminSystemRouteImport
      parentRoute: typeof TTenantAdminRoute
    }
    '/t/$tenant/admin/support': {
      id: '/t/$tenant/admin/support'
      path: '/support'
      fullPath: '/t/$tenant/admin/support'
      preLoaderRoute: typeof TTenantAdminSupportRouteImport
      parentRoute: typeof TTenantAdminRoute
    }
    '/t/$tenant/admin/billing': {
      id: '/t/$tenant/admin/billing'
      path: '/billing'
      fullPath: '/t/$tenant/admin/billing'
      preLoaderRoute: typeof TTenantAdminBillingRouteImport
      parentRoute: typeof TTenantAdminRoute
    }
    '/t/$tenant/admin/audit': {
      id: '/t/$tenant/admin/audit'
      path: '/audit'
      fullPath: '/t/$tenant/admin/audit'
      preLoaderRoute: typeof TTenantAdminAuditRouteImport
      parentRoute: typeof TTenantAdminRoute
    }
    '/t/$tenant/admin/agent': {
      id: '/t/$tenant/admin/agent'
      path: '/agent'
      fullPath: '/t/$tenant/admin/agent'
      preLoaderRoute: typeof TTenantAdminAgentRouteImport
      parentRoute: typeof TTenantAdminRoute
    }
  }
}

interface TTenantAdminRouteChildren {
  TTenantAdminAgentRoute: typeof TTenantAdminAgentRoute
  TTenantAdminAuditRoute: typeof TTenantAdminAuditRoute
  TTenantAdminBillingRoute: typeof TTenantAdminBillingRoute
  TTenantAdminSupportRoute: typeof TTenantAdminSupportRoute
  TTenantAdminSystemRoute: typeof TTenantAdminSystemRoute
  TTenantAdminUsersRoute: typeof TTenantAdminUsersRoute
}

const TTenantAdminRouteChildren: TTenantAdminRouteChildren = {
  TTenantAdminAgentRoute: TTenantAdminAgentRoute,
  TTenantAdminAuditRoute: TTenantAdminAuditRoute,
  TTenantAdminBillingRoute: TTenantAdminBillingRoute,
  TTenantAdminSupportRoute: TTenantAdminSupportRoute,
  TTenantAdminSystemRoute: TTenantAdminSystemRoute,
  TTenantAdminUsersRoute: TTenantAdminUsersRoute,
}

const TTenantAdminRouteWithChildren = TTenantAdminRoute._addFileChildren(
  TTenantAdminRouteChildren,
)

interface TTenantRouteChildren {
  TTenantAdminRoute: typeof TTenantAdminRouteWithChildren
  TTenantCustomersRoute: typeof TTenantCustomersRoute
  TTenantDashboardRoute: typeof TTenantDashboardRoute
  TTenantInvoicesRoute: typeof TTenantInvoicesRoute
  TTenantPaymentsRoute: typeof TTenantPaymentsRoute
  TTenantReportsRoute: typeof TTenantReportsRoute
  TTenantRoutesRoute: typeof TTenantRoutesRoute
  TTenantSettingsRoute: typeof TTenantSettingsRoute
}

const TTenantRouteChildren: TTenantRouteChildren = {
  TTenantAdminRoute: TTenantAdminRouteWithChildren,
  TTenantCustomersRoute: TTenantCustomersRoute,
  TTenantDashboardRoute: TTenantDashboardRoute,
  TTenantInvoicesRoute: TTenantInvoicesRoute,
  TTenantPaymentsRoute: TTenantPaymentsRoute,
  TTenantReportsRoute: TTenantReportsRoute,
  TTenantRoutesRoute: TTenantRoutesRoute,
  TTenantSettingsRoute: TTenantSettingsRoute,
}

const TTenantRouteWithChildren =
  TTenantRoute._addFileChildren(TTenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TTenantRoute: TTenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
